### PR TITLE
Rename Reference App Task

### PR DESCRIPTION
**Pull request by StephonBr**
- Created readme for creating construct app template and installing templates for clients
- Updated to .Net 6 by branching from .Net6 Branch
- Included template documents and nuget package documents as examples.

### CODE REVIEW

**Review by mdbrooks48 — CHANGES_REQUESTED** [review]
Can we rename the "FastForge.ReferenceApp.nuspec" file to "Construct.ReferenceApp.nuspec"?

**Comment by justjoehere** [comment]
I concur

**Comment by MCard** [comment]
Makes sense to me since it is a Centric Construct specific solution.
Probably need the person who coined the term "FastForge" to chime in too.

Mike Card
Centric Consulting
O: (888) 781-7567 | M: (630) 768-1986
www.centricconsulting.com<http://www.centricconsulting.com/>
Follow us: LinkedIn<https://www.linkedin.com/company/centric-consulting/> | Twitter<https://twitter.com/centric> | Facebook<https://facebook.com/CentricConsultingNational/>
[Logo-2C-14px]<http://www.linkedin.com/in/michael-card-3922b59>    Software Architect<https://centricconsulting.com/technology-solutions/>

**Comment by skopinskizzle** [comment]
I will dissent in simply that the name of the repo is FastForge-ReferenceApp-dotnet.  I think it we go with Construct, the repo should also be renamed.

**Comment by StephonBr** [comment]
Updated the file name. Sorry for marking you as a reviewer @MCard. I mistakenly clicked the wrong Mike moving to quickly.

**Pull request merged**
